### PR TITLE
add availability of existing device

### LINKED ISSUE #55: Add device availability of an existing device
On the page of a device, the user should be able to declare that she/her group has that device, i.e., in technical terms, to add a device availability.

### LINKED ISSUE #91: Design changes to Edit device availability popup
Popup is too large on some devices.

### PR DESCRIPTION
**Pull request by alasmaleki**

### CODE REVIEW

**Comment by alasmaleki** [comment]
fixes #91

**Review by chaoran-chen — CHANGES_REQUESTED** [review]
I am very sorry that it took me so long for the review!!

Only logged-in users should be allowed to add availabilities.

**Review by alasmaleki — COMMENTED** [review]
Requested changes fixed in last commit

**Comment by chaoran-chen** [comment]
Looks good :) Could you please just rebase it again?

**Review by chaoran-chen — APPROVED** [review]
Thank you!

**Pull request merged**
