### PR TITLE
Feature39/edit delete device availability

### PR DESCRIPTION
**Pull request by alasmaleki**

### CODE REVIEW

**Review by chaoran-chen — CHANGES_REQUESTED** [review]
I am having trouble to perform two actions right after each other. When I try to edit/delete a device availability after I already edited/deleted another device availability, I get the previous confirmation message again. I have to reload the page before doing another actions. Can you reproduce this bug?

**Comment by alasmaleki** [comment]
> I am having trouble to perform two actions right after each other. When I try to edit/delete a device availability after I already edited/deleted another device availability, I get the previous confirmation message again. I have to reload the page before doing another actions. Can you reproduce this bug?

Yes, thank you for mentioning, I must have made a mistake during my git history cleanup, since i did fix this issue in my last PR. hot-fix is in the next commit.

**Review by chaoran-chen — APPROVED** [review]
Thanks!

**Comment by alasmaleki** [comment]
closes #39

**Pull request merged**
