### PR TITLE
Feature/integrate design

### LINKED ISSUE #36: Integrate design concept
This issue requires collaboration with @FrEy0 who has created a design with color schemes and fonts for the webpage. Implement the design concept into the frontend.

### PR DESCRIPTION
**Pull request by benjiWdev**
closes #36. Next time we should create individual tickets for the different pages, I think.

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Some screenshots:

### Landing page


### Login


### Registration

**Review by chaoran-chen — COMMENTED** [review]
It looks beautiful but everything seems a little too big.

And maybe, also decrease the rounding a bit?

**Comment by chaoran-chen** [comment]
Is the ice bear a drawing of @FrEy0 or taken from the internet?

**Comment by FrEy0** [comment]
I drew it-but will improve it later :D I see that the colours don't fit

**Review by chaoran-chen — APPROVED** [review]
The code looks good 👍

**Pull request merged**
