### PR TITLE
Feature/device search

### LINKED ISSUE #7: Device overview with pagination
Create the webpage for the device search route.
On loading the page, the client is requesting all devices from the server and then listing them in an overview.
This site should has pagination for the frontend implemented. Every entry in the overview contains the title, the beginning of the device's description and a placeholder image.

- [ ] Create overview pages for devices
- [ ] Request devices from server and list them with pagination

API call: https://github.com/icebreaker-science/backend/issues/7

### PR DESCRIPTION
**Pull request by benjiWdev**

### CODE REVIEW

**Comment by chaoran-chen** [comment]
"Merge branch 'feature/device-search' of https://github.com/wird-in-5stunden-umbenannt/frontend into feature/device-search"?

The git history looks really weird^^ There are two commits "device-search basic layout" with the same changes. Could you maybe squash, rebase, or rename some commits?

**Comment by vordemann** [comment]
Completed requested rebase @chaoran-chen

**Comment by chaoran-chen** [comment]
That's not a rebase.. The aim is to have a clean and meaningful git history.

**Comment by chaoran-chen** [comment]
I mean, why do we now have commits belonging to an entirely other issue in this pull request?

**Review by chaoran-chen — APPROVED** [review]

**Pull request merged**
